# Generated by Django 2.2 on 2020-04-19 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_and_registration_app', '0002_auto_20200417_1231'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='photo',
            field=models.ImageField(blank=True, upload_to='profile_images'),
        ),
    ]
