# Generated by Django 2.2 on 2020-04-19 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_and_registration_app', '0004_auto_20200419_0846'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='default_photo',
            field=models.ImageField(default='profile_images/default.jpg', upload_to='profile_images'),
        ),
    ]
